# Generated by Django 3.2.12 on 2022-04-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackOrSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('level', models.IntegerField()),
                ('alignment', models.CharField(max_length=30)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('proficiencies', models.JSONField()),
                ('other_prof_languages', models.TextField(null=True)),
                ('inspiration', models.BooleanField(null=True)),
                ('personality', models.TextField(null=True)),
                ('ideals', models.TextField(null=True)),
                ('bonds', models.TextField(null=True)),
                ('flaws', models.TextField(null=True)),
                ('features', models.TextField(null=True)),
                ('maxHp', models.IntegerField()),
                ('currentHp', models.IntegerField()),
                ('inventory', models.JSONField(null=True)),
                ('notes', models.TextField(null=True)),
                ('attacks_and_spells', models.ManyToManyField(to='generator.AttackOrSpell')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.job')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='NpcModel',
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.race'),
        ),
        migrations.AddField(
            model_name='player',
            name='stuff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.stuff'),
        ),
    ]
